# Generated by Django 3.0.7 on 2020-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('run_id', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=20, null=True)),
                ('destination', models.CharField(max_length=20, null=True)),
                ('vessel_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
