# Generated by Django 3.0.7 on 2020-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='PARS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='PASS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='PCRS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='PCSS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='max_seats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
