# Generated by Django 3.0.7 on 2020-09-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leg', '0004_auto_20200917_1607'),
        ('leg', '0004_auto_20200917_1609'),
    ]

    operations = [
    ]
