# Generated by Django 3.0.7 on 2020-09-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20, null=True)),
                ('destination', models.CharField(max_length=20, null=True)),
                ('Mon', models.BooleanField(default=False)),
                ('Tue', models.BooleanField(default=False)),
                ('Wed', models.BooleanField(default=False)),
                ('Thu', models.BooleanField(default=False)),
                ('Fri', models.BooleanField(default=False)),
                ('Sat', models.BooleanField(default=False)),
                ('Sun', models.BooleanField(default=False)),
                ('vessel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vessel.Vessel')),
            ],
        ),
    ]
