# Generated by Django 3.0.7 on 2020-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20200915_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
