# Generated by Django 3.0.7 on 2020-09-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20, null=True)),
                ('destination', models.CharField(max_length=20, null=True)),
                ('vessel_name', models.CharField(max_length=20, null=True)),
                ('no_of_adults', models.PositiveSmallIntegerField()),
                ('no_of_children', models.PositiveSmallIntegerField()),
                ('journey_type', models.CharField(choices=[('S', 'Single'), ('R', 'Return')], default='S', max_length=1)),
                ('leg_id', models.PositiveSmallIntegerField(null=True)),
                ('booking_time', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
