# Generated by Django 3.0.7 on 2020-09-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_time',
            field=models.DateTimeField(null=True),
        ),
    ]
