# Generated by Django 3.0.7 on 2020-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200915_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
