# Generated by Django 3.0.7 on 2020-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200915_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger_details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
